name: firebase_notes
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^6.0.0
  firebase_core: ^4.0.0
  get: ^4.7.2
  google_sign_in: ^7.1.1
  mocktail: ^1.0.4
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
        - family: Allerta
          fonts:
            - asset: assets/fonts/Allerta-Regular.ttf
        - family: DidactGothic
          fonts:
            - asset: assets/fonts/DidactGothic-Regular.ttf