name: firebase_notes
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^6.0.0
  firebase_core: ^4.0.0
  get: ^4.7.2
  google_sign_in: ^7.1.1
  mocktail: ^1.0.4
  shared_preferences: ^2.5.3
  flutter_staggered_grid_view: ^0.7.0
  page_transition: ^2.2.1
  cloud_firestore: ^6.0.0
  intl: ^0.20.2
  skeletonizer: ^2.1.0+1
  flutter_native_splash: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/logo.png"
    background_color: "#ff151515"
    theme_color: "#ff151515"
  windows:
    generate: true
    image_path: "assets/logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
        - family: Allerta
          fonts:
            - asset: assets/fonts/Allerta-Regular.ttf
        - family: DidactGothic
          fonts:
            - asset: assets/fonts/DidactGothic-Regular.ttf
        - family: Inter
          fonts:
            - asset: assets/fonts/Inter.ttf